/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-21 02:28:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class afterLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1459747375077L));
    _jspx_dependants.put("jar:file:/C:/dev/jado_공은아/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectSample/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"Miminium Admin Template v.1\">\r\n");
      out.write("<meta name=\"author\" content=\"Isna Nur Azis\">\r\n");
      out.write("<meta name=\"keyword\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<title>JADo(JoinAndDo)</title>\r\n");
      out.write("\r\n");
      out.write("<!-- start: Css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- plugins -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/font-awesome.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/simple-line-icons.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/animate.min.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/fullcalendar.min.css\"/>   \r\n");
      out.write("<link href=\"resources/asset/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- prompt -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/themes/alertify.core.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/themes/alertify.default.css\" id=\"toggleCSS\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".alertify-log-custom {\r\n");
      out.write("\tbackground: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txtcenter {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- <a href=\"#\" id=\"prompt\">Prompt Dialog</a><br> -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<script src=\"resources/themes/alertify.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\tfunction reset () {\r\n");
      out.write("\t\t$(\"#toggleCSS\").attr(\"href\", \"resources/themes/alertify.default.css\");\r\n");
      out.write("\t\talertify.set({\r\n");
      out.write("\t\t\tlabels : {\r\n");
      out.write("\t\t\t\tok     : \"OK\",\r\n");
      out.write("\t\t\t\tcancel : \"Cancel\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdelay : 5000,\r\n");
      out.write("\t\t\tbuttonReverse : false,\r\n");
      out.write("\t\t\tbuttonFocus   : \"ok\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t$(\"#prompt\").on( 'click', function () {\r\n");
      out.write("\t\treset();\r\n");
      out.write("\t\talertify.prompt(\"Please input your project name\", function (e, str) {\r\n");
      out.write("\t\t\tif (e) {\r\n");
      out.write("\t\t\t\talertify.success(\"You've clicked OK and typed: \" + str);\r\n");
      out.write("\t\t\t\tvar usrNum = $('#usrNum').val();\r\n");
      out.write("\t\t\t\talert(typeof usrNum)\r\n");
      out.write("\t\t\t\tlocation.href=\"insertProject?title=\"+str+\"&userNum=\"+usrNum;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\talertify.error(\"You've clicked Cancel\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}, \"\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.goto').click(function(evetn){\r\n");
      out.write("\t\tevent.preventDefault();\r\n");
      out.write("\t\talert($(this).html())\r\n");
      out.write("\t\tvar x = $(this).parent().parent();\r\n");
      out.write("\t\tx.submit();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>\t\t\r\n");
      out.write("<!-- end: Css -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"resources/asset/img/logomi.png\">\r\n");
      out.write("<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("\t<script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write(" <body id=\"mimin\" class=\"dashboard\">\r\n");
      out.write("      <!-- start: Header -->\r\n");
      out.write("        <nav class=\"navbar navbar-default header navbar-fixed-top\">\r\n");
      out.write("          <div class=\"col-md-12 nav-wrapper\">\r\n");
      out.write("            <div class=\"navbar-header\" style=\"width:100%;\">\r\n");
      out.write("              <div class=\"opener-left-menu is-open\">\r\n");
      out.write("                <span class=\"top\"></span>\r\n");
      out.write("                <span class=\"middle\"></span>\r\n");
      out.write("                <span class=\"bottom\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("                <a href=\"index.html\" class=\"navbar-brand\"> \r\n");
      out.write("                 <b>JADo</b>\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("              <ul class=\"nav navbar-nav navbar-right user-nav\">\r\n");
      out.write("              \t<li class=\"dropdown avatar-dropdown\">\r\n");
      out.write("                   <img src=\"resources/asset/img/avatar.jpg\" class=\"img-circle avatar\" alt=\"user name\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\"/>\r\n");
      out.write("                   <ul class=\"dropdown-menu user-dropdown\">\r\n");
      out.write("                     <li><a href=\"#\"><span class=\"fa fa-user\"></span> My Profile</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><span class=\"fa fa-calendar\"></span> My Calendar</a></li>\r\n");
      out.write("                     <li role=\"separator\" class=\"divider\"></li>\r\n");
      out.write("                     <li class=\"more\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"\"><span class=\"fa fa-cogs\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\"><span class=\"fa fa-lock\"></span></a></li>\r\n");
      out.write("                        <li><a href=\"\"><span class=\"fa fa-power-off \"></span></a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>&nbsp;</li>\r\n");
      out.write("                <li class=\"user-name\"><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("      <!-- end: Header -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container-fluid mimin-wrapper\">\r\n");
      out.write("  \r\n");
      out.write("          <!-- start:Left Menu -->\r\n");
      out.write("            <div id=\"left-menu\">\r\n");
      out.write("              <div class=\"sub-left-menu scroll\">\r\n");
      out.write("                <ul class=\"nav nav-list\">\r\n");
      out.write("                    <li><div class=\"left-bg\"></div></li>\r\n");
      out.write("                    <li class=\"time\">\r\n");
      out.write("                      <h1 class=\"animated fadeInLeft\">21:00</h1>\r\n");
      out.write("                      <p class=\"animated fadeInRight\">Sat,October 1st 2029</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\"><a class=\"tree-toggle nav-header\"><span class=\"icons icon-user\">\r\n");
      out.write("                    </span> Account Setting  <span class=\"fa-angle-right fa right-arrow text-right\"></span> </a>\r\n");
      out.write("                    \t<ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"loginView\">SignIn</a></li>\r\n");
      out.write("                        <li><a href=\"joinView\">SignUp</a></li>\r\n");
      out.write("                        <li><a href=\"logout\">SignOut</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\"><a href=\"#\"><span class=\"fa fa-folder-o\"></span> Clip  <span class=\"fa-angle-right fa right-arrow text-right\"></span></a></li>\r\n");
      out.write("                    <li class=\"ripple\"><a href=\"#\"><span class=\"icons icon-list\"></span> Project List  <span class=\"fa-angle-right fa right-arrow text-right\"></span></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          <!-- end: Left Menu -->\r\n");
      out.write("\r\n");
      out.write("  \t\t\r\n");
      out.write("          <!-- start: content -->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("                <div class=\"col-md-12\" style=\"padding:20px;\">\r\n");
      out.write("                  <div class=\"panel col-md-12 padding-0\">\r\n");
      out.write("                      <div class=\"panel-heading txtcenter\">\r\n");
      out.write("                        <h3>Project List</h3>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                      <div class=\"panel-body txtcenter\" style=\"padding-bottom: 0px; padding-top: 0px;\">    \r\n");
      out.write("                          <hr />\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"panel-body txtcenter\" style=\"padding-top: 0px;\">\r\n");
      out.write("                          <h4><a href=\"#\" id=\"prompt\">+ 새로운 프로젝트 생성하기</a\t></h4>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("      \t\t  </div>\r\n");
      out.write("          <!-- end: content -->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- start: Mobile -->\r\n");
      out.write("      <div id=\"mimin-mobile\" class=\"reverse\">\r\n");
      out.write("        <div class=\"mimin-mobile-menu-list\">\r\n");
      out.write("            <div class=\"col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft\">\r\n");
      out.write("                <ul class=\"nav nav-list\">\r\n");
      out.write("                    <li class=\"active ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa-home fa\"></span>Dashboard \r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                          <li><a href=\"dashboard-v1.html\">Dashboard v.1</a></li>\r\n");
      out.write("                          <li><a href=\"dashboard-v2.html\">Dashboard v.2</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa-diamond fa\"></span>Layout\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"topnav.html\">Top Navigation</a></li>\r\n");
      out.write("                        <li><a href=\"boxed.html\">Boxed</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa-area-chart fa\"></span>Charts\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"chartjs.html\">ChartJs</a></li>\r\n");
      out.write("                        <li><a href=\"morris.html\">Morris</a></li>\r\n");
      out.write("                        <li><a href=\"flot.html\">Flot</a></li>\r\n");
      out.write("                        <li><a href=\"sparkline.html\">SparkLine</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-pencil-square\"></span>Ui Elements\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"color.html\">Color</a></li>\r\n");
      out.write("                        <li><a href=\"weather.html\">Weather</a></li>\r\n");
      out.write("                        <li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("                        <li><a href=\"icons.html\">Icons</a></li>\r\n");
      out.write("                        <li><a href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("                        <li><a href=\"media.html\">Media</a></li>\r\n");
      out.write("                        <li><a href=\"panels.html\">Panels & Tabs</a></li>\r\n");
      out.write("                        <li><a href=\"notifications.html\">Notifications & Tooltip</a></li>\r\n");
      out.write("                        <li><a href=\"badges.html\">Badges & Label</a></li>\r\n");
      out.write("                        <li><a href=\"progress.html\">Progress</a></li>\r\n");
      out.write("                        <li><a href=\"sliders.html\">Sliders</a></li>\r\n");
      out.write("                        <li><a href=\"timeline.html\">Timeline</a></li>\r\n");
      out.write("                        <li><a href=\"modal.html\">Modals</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                       <span class=\"fa fa-check-square-o\"></span>Forms\r\n");
      out.write("                       <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"formelement.html\">Form Element</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Wizard</a></li>\r\n");
      out.write("                        <li><a href=\"#\">File Upload</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Text Editor</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-table\"></span>Tables\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"datatables.html\">Data Tables</a></li>\r\n");
      out.write("                        <li><a href=\"handsontable.html\">handsontable</a></li>\r\n");
      out.write("                        <li><a href=\"tablestatic.html\">Static</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a href=\"calendar.html\">\r\n");
      out.write("                         <span class=\"fa fa-calendar-o\"></span>Calendar\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-envelope-o\"></span>Mail\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"mail-box.html\">Inbox</a></li>\r\n");
      out.write("                        <li><a href=\"compose-mail.html\">Compose Mail</a></li>\r\n");
      out.write("                        <li><a href=\"view-mail.html\">View Mail</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-file-code-o\"></span>Pages\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"forgotpass.html\">Forgot Password</a></li>\r\n");
      out.write("                        <li><a href=\"login.html\">SignIn</a></li>\r\n");
      out.write("                        <li><a href=\"reg.html\">SignUp</a></li>\r\n");
      out.write("                        <li><a href=\"article-v1.html\">Article v1</a></li>\r\n");
      out.write("                        <li><a href=\"search-v1.html\">Search Result v1</a></li>\r\n");
      out.write("                        <li><a href=\"productgrid.html\">Product Grid</a></li>\r\n");
      out.write("                        <li><a href=\"profile-v1.html\">Profile v1</a></li>\r\n");
      out.write("                        <li><a href=\"invoice-v1.html\">Invoice v1</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li class=\"ripple\"><a class=\"tree-toggle nav-header\"><span class=\"fa \"></span> MultiLevel  <span class=\"fa-angle-right fa right-arrow text-right\"></span> </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"view-mail.html\">Level 1</a></li>\r\n");
      out.write("                        <li><a href=\"view-mail.html\">Level 1</a></li>\r\n");
      out.write("                        <li class=\"ripple\">\r\n");
      out.write("                          <a class=\"sub-tree-toggle nav-header\">\r\n");
      out.write("                            <span class=\"fa fa-envelope-o\"></span> Level 1\r\n");
      out.write("                            <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                          </a>\r\n");
      out.write("                          <ul class=\"nav nav-list sub-tree\">\r\n");
      out.write("                            <li><a href=\"mail-box.html\">Level 2</a></li>\r\n");
      out.write("                            <li><a href=\"compose-mail.html\">Level 2</a></li>\r\n");
      out.write("                            <li><a href=\"view-mail.html\">Level 2</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"credits.html\">Credits</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>       \r\n");
      out.write("      </div>\r\n");
      out.write("      <button id=\"mimin-mobile-menu-opener\" class=\"animated rubberBand btn btn-circle btn-danger\">\r\n");
      out.write("        <span class=\"fa fa-bars\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("       <!-- end: Mobile -->\r\n");
      out.write("\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id='usrNum'>\r\n");
      out.write("    <!-- start: Javascript -->\r\n");
      out.write("    <script src=\"resources/asset/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/jquery.ui.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/bootstrap.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    <!-- plugins -->\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/fullcalendar.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/jquery.nicescroll.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/jquery.vmap.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/jquery.vmap.sampledata.js\"></script>\r\n");
      out.write("    <script src=\"resources/asset/js/plugins/chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- custom -->\r\n");
      out.write("     <script src=\"resources/asset/js/main.js\"></script>\r\n");
      out.write("     <script type=\"text/javascript\">\r\n");
      out.write("      (function(jQuery){\r\n");
      out.write("\r\n");
      out.write("        // start: Chart =============\r\n");
      out.write("\r\n");
      out.write("        Chart.defaults.global.pointHitDetectionRadius = 1;\r\n");
      out.write("        Chart.defaults.global.customTooltips = function(tooltip) {\r\n");
      out.write("\r\n");
      out.write("            var tooltipEl = $('#chartjs-tooltip');\r\n");
      out.write("\r\n");
      out.write("            if (!tooltip) {\r\n");
      out.write("                tooltipEl.css({\r\n");
      out.write("                    opacity: 0\r\n");
      out.write("                });\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            tooltipEl.removeClass('above below');\r\n");
      out.write("            tooltipEl.addClass(tooltip.yAlign);\r\n");
      out.write("\r\n");
      out.write("            var innerHtml = '';\r\n");
      out.write("            if (undefined !== tooltip.labels && tooltip.labels.length) {\r\n");
      out.write("                for (var i = tooltip.labels.length - 1; i >= 0; i--) {\r\n");
      out.write("                    innerHtml += [\r\n");
      out.write("                        '<div class=\"chartjs-tooltip-section\">',\r\n");
      out.write("                        '   <span class=\"chartjs-tooltip-key\" style=\"background-color:' + tooltip.legendColors[i].fill + '\"></span>',\r\n");
      out.write("                        '   <span class=\"chartjs-tooltip-value\">' + tooltip.labels[i] + '</span>',\r\n");
      out.write("                        '</div>'\r\n");
      out.write("                    ].join('');\r\n");
      out.write("                }\r\n");
      out.write("                tooltipEl.html(innerHtml);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            tooltipEl.css({\r\n");
      out.write("                opacity: 1,\r\n");
      out.write("                left: tooltip.chart.canvas.offsetLeft + tooltip.x + 'px',\r\n");
      out.write("                top: tooltip.chart.canvas.offsetTop + tooltip.y + 'px',\r\n");
      out.write("                fontFamily: tooltip.fontFamily,\r\n");
      out.write("                fontSize: tooltip.fontSize,\r\n");
      out.write("                fontStyle: tooltip.fontStyle\r\n");
      out.write("            });\r\n");
      out.write("        };\r\n");
      out.write("        var randomScalingFactor = function() {\r\n");
      out.write("            return Math.round(Math.random() * 100);\r\n");
      out.write("        };\r\n");
      out.write("        var lineChartData = {\r\n");
      out.write("            labels: [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\"],\r\n");
      out.write("            datasets: [{\r\n");
      out.write("                label: \"My First dataset\",\r\n");
      out.write("                fillColor: \"rgba(21,186,103,0.4)\",\r\n");
      out.write("                strokeColor: \"rgba(220,220,220,1)\",\r\n");
      out.write("                pointColor: \"rgba(66,69,67,0.3)\",\r\n");
      out.write("                pointStrokeColor: \"#fff\",\r\n");
      out.write("                pointHighlightFill: \"#fff\",\r\n");
      out.write("                pointHighlightStroke: \"rgba(220,220,220,1)\",\r\n");
      out.write("                 data: [18,9,5,7,4.5,4,5,4.5,6,5.6,7.5]\r\n");
      out.write("            }, {\r\n");
      out.write("                label: \"My Second dataset\",\r\n");
      out.write("                fillColor: \"rgba(21,113,186,0.5)\",\r\n");
      out.write("                strokeColor: \"rgba(151,187,205,1)\",\r\n");
      out.write("                pointColor: \"rgba(151,187,205,1)\",\r\n");
      out.write("                pointStrokeColor: \"#fff\",\r\n");
      out.write("                pointHighlightFill: \"#fff\",\r\n");
      out.write("                pointHighlightStroke: \"rgba(151,187,205,1)\",\r\n");
      out.write("                data: [4,7,5,7,4.5,4,5,4.5,6,5.6,7.5]\r\n");
      out.write("            }]\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var doughnutData = [\r\n");
      out.write("                {\r\n");
      out.write("                    value: 300,\r\n");
      out.write("                    color:\"#129352\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Alfa\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 50,\r\n");
      out.write("                    color: \"#1AD576\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Beta\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 100,\r\n");
      out.write("                    color: \"#FDB45C\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Gamma\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 40,\r\n");
      out.write("                    color: \"#0F5E36\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Peta\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 120,\r\n");
      out.write("                    color: \"#15A65D\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"X\"\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        var doughnutData2 = [\r\n");
      out.write("                {\r\n");
      out.write("                    value: 100,\r\n");
      out.write("                    color:\"#129352\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Alfa\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 250,\r\n");
      out.write("                    color: \"#FF6656\",\r\n");
      out.write("                    highlight: \"#FF6656\",\r\n");
      out.write("                    label: \"Beta\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 100,\r\n");
      out.write("                    color: \"#FDB45C\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Gamma\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 40,\r\n");
      out.write("                    color: \"#FD786A\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"Peta\"\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    value: 120,\r\n");
      out.write("                    color: \"#15A65D\",\r\n");
      out.write("                    highlight: \"#15BA67\",\r\n");
      out.write("                    label: \"X\"\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            ];\r\n");
      out.write("\r\n");
      out.write("        var barChartData = {\r\n");
      out.write("                labels: [\"January\", \"February\", \"March\", \"April\", \"May\", \"June\", \"July\"],\r\n");
      out.write("                datasets: [\r\n");
      out.write("                    {\r\n");
      out.write("                        label: \"My First dataset\",\r\n");
      out.write("                        fillColor: \"rgba(21,186,103,0.4)\",\r\n");
      out.write("                        strokeColor: \"rgba(220,220,220,0.8)\",\r\n");
      out.write("                        highlightFill: \"rgba(21,186,103,0.2)\",\r\n");
      out.write("                        highlightStroke: \"rgba(21,186,103,0.2)\",\r\n");
      out.write("                        data: [65, 59, 80, 81, 56, 55, 40]\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        label: \"My Second dataset\",\r\n");
      out.write("                        fillColor: \"rgba(21,113,186,0.5)\",\r\n");
      out.write("                        strokeColor: \"rgba(151,187,205,0.8)\",\r\n");
      out.write("                        highlightFill: \"rgba(21,113,186,0.2)\",\r\n");
      out.write("                        highlightStroke: \"rgba(21,113,186,0.2)\",\r\n");
      out.write("                        data: [28, 48, 40, 19, 86, 27, 90]\r\n");
      out.write("                    }\r\n");
      out.write("                ]\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        //  end:  Chart =============\r\n");
      out.write("\r\n");
      out.write("        // start: Calendar =========\r\n");
      out.write("         $('.dashboard .calendar').fullCalendar({\r\n");
      out.write("            header: {\r\n");
      out.write("                left: 'prev,next today',\r\n");
      out.write("                center: 'title',\r\n");
      out.write("                right: 'month,agendaWeek,agendaDay'\r\n");
      out.write("            },\r\n");
      out.write("            defaultDate: '2015-02-12',\r\n");
      out.write("            businessHours: true, // display business hours\r\n");
      out.write("            editable: true,\r\n");
      out.write("            events: [\r\n");
      out.write("                {\r\n");
      out.write("                    title: 'Business Lunch',\r\n");
      out.write("                    start: '2015-02-03T13:00:00',\r\n");
      out.write("                    constraint: 'businessHours'\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    title: 'Meeting',\r\n");
      out.write("                    start: '2015-02-13T11:00:00',\r\n");
      out.write("                    constraint: 'availableForMeeting', // defined below\r\n");
      out.write("                    color: '#20C572'\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    title: 'Conference',\r\n");
      out.write("                    start: '2015-02-18',\r\n");
      out.write("                    end: '2015-02-20'\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    title: 'Party',\r\n");
      out.write("                    start: '2015-02-29T20:00:00'\r\n");
      out.write("                },\r\n");
      out.write("\r\n");
      out.write("                // areas where \"Meeting\" must be dropped\r\n");
      out.write("                {\r\n");
      out.write("                    id: 'availableForMeeting',\r\n");
      out.write("                    start: '2015-02-11T10:00:00',\r\n");
      out.write("                    end: '2015-02-11T16:00:00',\r\n");
      out.write("                    rendering: 'background'\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    id: 'availableForMeeting',\r\n");
      out.write("                    start: '2015-02-13T10:00:00',\r\n");
      out.write("                    end: '2015-02-13T16:00:00',\r\n");
      out.write("                    rendering: 'background'\r\n");
      out.write("                },\r\n");
      out.write("\r\n");
      out.write("                // red areas where no events can be dropped\r\n");
      out.write("                {\r\n");
      out.write("                    start: '2015-02-24',\r\n");
      out.write("                    end: '2015-02-28',\r\n");
      out.write("                    overlap: false,\r\n");
      out.write("                    rendering: 'background',\r\n");
      out.write("                    color: '#FF6656'\r\n");
      out.write("                },\r\n");
      out.write("                {\r\n");
      out.write("                    start: '2015-02-06',\r\n");
      out.write("                    end: '2015-02-08',\r\n");
      out.write("                    overlap: true,\r\n");
      out.write("                    rendering: 'background',\r\n");
      out.write("                    color: '#FF6656'\r\n");
      out.write("                }\r\n");
      out.write("            ]\r\n");
      out.write("        });\r\n");
      out.write("        // end : Calendar==========\r\n");
      out.write("\r\n");
      out.write("        // start: Maps============\r\n");
      out.write("\r\n");
      out.write("          jQuery('.maps').vectorMap({\r\n");
      out.write("            map: 'world_en',\r\n");
      out.write("            backgroundColor: null,\r\n");
      out.write("            color: '#fff',\r\n");
      out.write("            hoverOpacity: 0.7,\r\n");
      out.write("            selectedColor: '#666666',\r\n");
      out.write("            enableZoom: true,\r\n");
      out.write("            showTooltip: true,\r\n");
      out.write("            values: sample_data,\r\n");
      out.write("            scaleColors: ['#C8EEFF', '#006491'],\r\n");
      out.write("            normalizeFunction: 'polynomial'\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // end: Maps==============\r\n");
      out.write("\r\n");
      out.write("      })(jQuery);\r\n");
      out.write("     </script>\r\n");
      out.write("  <!-- end: Javascript -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/afterLogin.jsp(164,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("list");
    // /WEB-INF/views/afterLogin.jsp(164,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/afterLogin.jsp(164,22) '${pList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                      <div class=\"panel-body txtcenter\">\r\n");
          out.write("\t                          <div>\r\n");
          out.write("\t                          \r\n");
          out.write("\t                          <form action=\"gotoGroup\" id='goto' method=\"get\">\r\n");
          out.write("\t                          \t<h4><a href=\"#\" class=\"goto\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></h4>\r\n");
          out.write("\t                          \t<input type=\"text\" name=\"proNum\", value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.proNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t                          </form>\r\n");
          out.write("\t                          \t<h5>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h5>\r\n");
          out.write("\t                          </div>\r\n");
          out.write("\t                      </div>\r\n");
          out.write("                      ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
