/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-21 02:28:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chatbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1459747375077L));
    _jspx_dependants.put("jar:file:/C:/dev/jado_공은아/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectSample/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"description\" content=\"Miminium Admin Template v.1\">\r\n");
      out.write("\t<meta name=\"author\" content=\"Isna Nur Azis\">\r\n");
      out.write("\t<meta name=\"keyword\" content=\"\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <title>Chatting Room</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- start: Css -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- plugins -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/font-awesome.min.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/simple-line-icons.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/mediaelementplayer.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"resources/asset/css/plugins/animate.min.css\"/>\r\n");
      out.write("  <link href=\"resources/asset/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- end: Css -->\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"resources/asset/img/logomi.png\">\r\n");
      out.write("  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("      <![endif]-->\r\n");
      out.write("      \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".col-md-12 { margin: 0 }\r\n");
      out.write(".fa:hover {\r\n");
      out.write("    color: gray;\r\n");
      out.write("}\r\n");
      out.write("</style> \r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"resources/jquery.selection.js\"></script>\r\n");
      out.write("<script src=\"resources/notify.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$('#upload').on('click',function(){\r\n");
      out.write("\t\t$('#saveFile').trigger('click');\r\n");
      out.write("\t})\r\n");
      out.write("\t$(\"input[type='file']\").on(\"change\", function(){\r\n");
      out.write("\t\tvar formData = new FormData();\r\n");
      out.write("\t\tvar file = this.files[0];                      //multiple 속성이 있으면 files 에는 다수의 객체가 할당됨\r\n");
      out.write("\t\tformData.append(\"imgFile\", file);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\tasync : true,\r\n");
      out.write("\t\tmethod : \"post\",\r\n");
      out.write("\t\turl : 'fileupload',\r\n");
      out.write("\t\tprocessData : false, //true : data의 파일형태가 query String으로 전송. false : non-processed data \r\n");
      out.write("\t\tdata : formData,\r\n");
      out.write("\t\tcontentType : false, // false : multipart/form-data 형태로 전송되기 위한 옵션값\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t       \tvar msg = {\r\n");
      out.write("        \t\t\t\"usrName\":nickname, \"way\":\"download\", \"content\":data\r\n");
      out.write("        \t\t};\r\n");
      out.write("       \tvar jsonStr = JSON.stringify(msg);\r\n");
      out.write("\t\tws.send(jsonStr);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t$('#hangOut').on('click',function(){\r\n");
      out.write("\t\tlocation.href=\"http://203.233.196.85:8888/app/\"\r\n");
      out.write("\t})\r\n");
      out.write("\tdocument.getElementById('targetId').scrollTop = document.getElementById('targetId').scrollHeight;\r\n");
      out.write("\tconnect();\r\n");
      out.write("\t\r\n");
      out.write("\t$('.timeline').on('mouseup',function(){\r\n");
      out.write("\t\tvar target = $.selection();\r\n");
      out.write("\t\tif(target.length==0){\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tvar msg = {\r\n");
      out.write("\t\t\t\t\"usrName\":target, \"phone\":\"010-1234-6543\", \"content\":\"Hello World, 감사합니다\"\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\tvar jsonStr = JSON.stringify(msg);\r\n");
      out.write("\t\t\tws.send(jsonStr);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#chat').keyup(send);\r\n");
      out.write("\t$('#openCal').on('click',function(){\r\n");
      out.write("\t\tvar msg = {\r\n");
      out.write("    \t\t\t\"usrName\":nickname, \"way\":\"cal\", \"content\":''\r\n");
      out.write("    \t\t};\r\n");
      out.write("\t\tvar jsonStr = JSON.stringify(msg);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(jsonStr)\r\n");
      out.write("\t\tws.send(jsonStr);\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#recordStart').on('click',function(){\r\n");
      out.write("\t\t$(\"#result\").append(\"<h4>회의록 저장 시작</h4>\")\r\n");
      out.write("\t\tswap=\"record\"\r\n");
      out.write("\t\tdocument.getElementById('targetId').scrollTop = document.getElementById('targetId').scrollHeight;\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#recordEnd').on('click',function(){\r\n");
      out.write("\t\tswap=\"unRecord\";\r\n");
      out.write("\t\t$(\"#result\").append(\"<h4>회의록 저장 종료</h4>\")\r\n");
      out.write("\t\tdocument.getElementById('targetId').scrollTop = document.getElementById('targetId').scrollHeight;\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//Visible api\r\n");
      out.write("function getHiddenProp(){\r\n");
      out.write("    var prefixes = ['webkit','moz','ms','o'];\r\n");
      out.write("    \r\n");
      out.write("    // if 'hidden' is natively supported just return it\r\n");
      out.write("    if ('hidden' in document) return 'hidden';\r\n");
      out.write("    \r\n");
      out.write("    // otherwise loop over all the known prefixes until we find one\r\n");
      out.write("    for (var i = 0; i < prefixes.length; i++){\r\n");
      out.write("        if ((prefixes[i] + 'Hidden') in document) \r\n");
      out.write("            return prefixes[i] + 'Hidden';\r\n");
      out.write("    }\r\n");
      out.write("    // otherwise it's not supported\r\n");
      out.write("    return null;\r\n");
      out.write("}\r\n");
      out.write("function isHidden() {\r\n");
      out.write("    var prop = getHiddenProp();\r\n");
      out.write("    if (!prop) return false;\r\n");
      out.write("    \r\n");
      out.write("    return document[prop];\r\n");
      out.write("}\r\n");
      out.write("window.addEventListener(\"load\", function simpleDemo() {\r\n");
      out.write("  // use the property name to generate the prefixed event name\r\n");
      out.write("  var visProp = getHiddenProp();\r\n");
      out.write("  if (visProp) {\r\n");
      out.write("    var evtname = visProp.replace(/[H|h]idden/,'') + 'visibilitychange';\r\n");
      out.write("    document.addEventListener(evtname, visChange);\r\n");
      out.write("  }\r\n");
      out.write("  else {\r\n");
      out.write("  }\r\n");
      out.write("\tfunction visChange() {\r\n");
      out.write("\t\t\tif (isHidden()) {\r\n");
      out.write("      }\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//NOtification Api\r\n");
      out.write("function pushNoti(data){\r\n");
      out.write("\t function onShowNotification () {\r\n");
      out.write("   }\r\n");
      out.write("   function onCloseNotification () {\r\n");
      out.write("   }\r\n");
      out.write("   function onClickNotification () {\r\n");
      out.write("   }\r\n");
      out.write("   function onErrorNotification () {\r\n");
      out.write("   }\r\n");
      out.write("   function onPermissionGranted () {\r\n");
      out.write("       doNotification();\r\n");
      out.write("   }\r\n");
      out.write("   function onPermissionDenied () {\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function doNotification () {\r\n");
      out.write("   //\t \tvar xx = data.split('\\\\\":\\\\\"')\r\n");
      out.write("   \t// \tvar data2 = xx[3].split('\\\\')\r\n");
      out.write("   \t \t\r\n");
      out.write("       var myNotification = new Notify(data.sender, {\r\n");
      out.write("           body: data.content,\r\n");
      out.write("           tag: data.sender,\r\n");
      out.write("           notifyShow: onShowNotification,\r\n");
      out.write("           notifyClose: onCloseNotification,\r\n");
      out.write("           notifyClick: onClickNotification,\r\n");
      out.write("           notifyError: onErrorNotification,\r\n");
      out.write("           timeout: 4\r\n");
      out.write("       });\r\n");
      out.write("  \r\n");
      out.write("       myNotification.show();\r\n");
      out.write("   }\r\n");
      out.write("   if (!Notify.needsPermission) {\r\n");
      out.write("  \t doNotification();\r\n");
      out.write("   } else if (Notify.isSupported()) {\r\n");
      out.write("       Notify.requestPermission(onPermissionGranted, onPermissionDenied);\r\n");
      out.write("   }    \r\n");
      out.write("}\r\n");
      out.write("//WebSocket Api\r\n");
      out.write("var url = window.location.href;\r\n");
      out.write("\tvar arr = url.split(\"=\")\r\n");
      out.write("var ws = null;\r\n");
      out.write("var nickname= \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("var swap ;\r\n");
      out.write("var proNum = arr[1]\r\n");
      out.write("proNum=proNum.split(\"&\")[0];\r\n");
      out.write("var theme = arr[2];\r\n");
      out.write("function connect() {\r\n");
      out.write("  // 아래의 적색 경로는 서버측의 ServerEndPoint 를 사용해야 하고 ? 표시 오른쪽에는 파라미터가 온다\r\n");
      out.write("\t\t  var target = \"ws://203.233.196.76:8666/app/echo?usr=\"+nickname+\"&Pnum=\"+proNum+\"&Theme=\"+theme; //서버에서 파라미터를 \r\n");
      out.write("if ('WebSocket' in window) {\r\n");
      out.write("     ws = new WebSocket(target);\r\n");
      out.write("     alert('dsdsds')\r\n");
      out.write("     var x =arr[3];\r\n");
      out.write("     $('#meetingRoom').text(x.replace(/%20/,' '));\r\n");
      out.write("} else if ('MozWebSocket' in window) {\r\n");
      out.write("     ws = new MozWebSocket(target);\r\n");
      out.write("     \r\n");
      out.write(" } else {\r\n");
      out.write("     return;\r\n");
      out.write(" }\r\n");
      out.write(" ws.onopen = function () {\r\n");
      out.write("\t document.getElementById('chat').onkeydown = function(event) {\r\n");
      out.write("\t\t if (event.keyCode == 13) {\r\n");
      out.write("             send();\r\n");
      out.write("         }\r\n");
      out.write("     };\r\n");
      out.write(" };\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" function swapping(data){\r\n");
      out.write("\t swap=data\r\n");
      out.write("\t alert(swap)\r\n");
      out.write(" }\r\n");
      out.write(" ws.onmessage = function (event) {\r\n");
      out.write("\t if(event.data.match(/cal/)){\r\n");
      out.write("\t\t\t$(\"#result\").append(\"<a href ='javascript:openCal()''>일정잡기\"+'</a><br />')\r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t var data = event.data.split(\":\")\r\n");
      out.write("\t\t var sender = data[1].split(\",\");\r\n");
      out.write("\t\t sender[0].replace(/\"/g,'')\r\n");
      out.write("\t\t var content = data[3].substr(0,data[3].length-2)\r\n");
      out.write("\t\t var asClass\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t if(sender[0].replace(/\"/g,'')==nickname) {\r\n");
      out.write("\t\t\tasClass = \"timeline-inverted\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t$(\"#result\").append(\"<li class='\"+asClass+\"'><div class='timeline-panel'><div class='timeline-heading'><h4 class='timeline-title'>\"+sender[0].replace(/\"/g,'')+\r\n");
      out.write("\t\t\t\t\"</h4></div><div class='timeline-body'>\"+content+\"</div></div></li>\")\r\n");
      out.write("\tnotif=event.data\r\n");
      out.write("\t\r\n");
      out.write("\tif (isHidden()) {\r\n");
      out.write("\t\tif(notif==null){}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\tpushNoti(notif)\r\n");
      out.write("\t\tnotif=null\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\telse {\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("\tdocument.getElementById('targetId').scrollTop = document.getElementById('targetId').scrollHeight;\r\n");
      out.write("\tif(swap ===\"record\"){\r\n");
      out.write("\t\tvar mydata={\r\n");
      out.write("\t\t\t\t\"sender\" : nickname,\r\n");
      out.write("\t\t\t\t\"content\" : content\r\n");
      out.write("\t\t\t\t,\"proNum\" : proNum\r\n");
      out.write("\t\t\t\t,\"thmNum\" : theme.split('&')[0]\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tmydata = JSON.stringify(mydata);\r\n");
      out.write("\t\t\tmydata=$.ajax({\r\n");
      out.write("\t\t\t\tmethod:\"post\"\r\n");
      out.write("\t\t\t\t,url:\"record\"\r\n");
      out.write("\t\t\t\t,data:mydata\r\n");
      out.write("\t\t\t\t,dataType:\"json\"\r\n");
      out.write("\t\t\t\t,contentType:\"application/json;charset=utf-8\"\r\n");
      out.write("\t\t\t\t,success:function(response){\r\n");
      out.write("\t\t\t\t\tvar json =response\r\n");
      out.write("\t\t\t\talert(json)\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},error:function(response){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write(" };\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ws.onclose = function () {\r\n");
      out.write(" };\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function send() {// JSON 문자열을 서버로 전송한다\r\n");
      out.write("\tif(event.keyCode===13){\r\n");
      out.write("\tvar message = $('#chat').val();\r\n");
      out.write("\tif (message != '') {\r\n");
      out.write("        \tvar msg = {\r\n");
      out.write("        \t\t\t\"usrName\":nickname, \"way\":\"chat\", \"content\":message\r\n");
      out.write("        \t\t};\r\n");
      out.write("       \tvar jsonStr = JSON.stringify(msg);\r\n");
      out.write("\t\tws.send(jsonStr);\r\n");
      out.write("            document.getElementById('chat').value = '';\r\n");
      out.write("        }\r\n");
      out.write("\t}\r\n");
      out.write("    //});\r\n");
      out.write("}\r\n");
      out.write("function openCal(){\r\n");
      out.write("//\t$('#cal').attr('src','cal')\r\n");
      out.write("//\t$('#cal').css('display','block')\r\n");
      out.write("\tvar popUrl = \"cal\";\t//팝업창에 출력될 페이지 URL\r\n");
      out.write("\tvar popOption = \"width=550, height=360, resizable=no, scrollbars=no, status=no;\";    //팝업창 옵션(optoin)\r\n");
      out.write("\t\twindow.open(popUrl,\"\",popOption);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>     \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"mimin\" class=\"dashboard topnav\">\r\n");
      out.write("<form id=\"frm\" action=\"fileupload\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"file\" id=\"saveFile\" style=\"display: none\">\t\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("      <!-- start: Content -->\r\n");
      out.write("          <div class=\"col-md-12 top-20 padding-0\">\r\n");
      out.write("            <div class=\"col-md-12 padding-0\">\r\n");
      out.write("            <div class=\"panel\">\r\n");
      out.write("              <div class=\"panel-heading\"><h3 id=\"meetingRoom\">회의실</h3></div>\r\n");
      out.write("              <div class=\"panel-body\">\r\n");
      out.write("                <div class=\"col-md-12\" id=\"targetId\" style=\"overflow:scroll; height: 800px\">\r\n");
      out.write("                  <ul class=\"timeline\" id=\"result\">\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div class=\"chat_input\">\r\n");
      out.write("\t            <div class=\"panel-heading\">\r\n");
      out.write("\t            \t<input type=\"text\" size=\"95%\" placeholder=\"please input your text here...\" id=\"chat\" />&nbsp;\r\n");
      out.write("\t            \t<input type=\"button\" class=\"btn btn-round btn-primary\" value=\"send\" style=\"height: 40px; width: auto;\">\r\n");
      out.write("\t            \t<br />\r\n");
      out.write("\t            \t<!-- íìì -->\r\n");
      out.write("\t\t\t\t\t<a><i class=\"fa fa-phone\" id=\"hangOut\" style=\"font-size: 30px;\"></i></a>&nbsp;\r\n");
      out.write("\t\t\t\t\t<!-- íì¼ ìë¡ë -->\r\n");
      out.write("\t\t\t\t\t<a><i class=\"fa fa-upload\" id=\"upload\" style=\"font-size: 30px;\"></i></a>&nbsp;\r\n");
      out.write("\t\t\t\t\t<!-- ì¼ì ì¡ê¸° -->\r\n");
      out.write("\t\t\t\t\t<a><i class=\"fa fa-calendar\" id=\"openCal\" style=\"font-size: 30px;\"></i></a>&nbsp;\r\n");
      out.write("\t\t\t\t\t<!-- íìë¡ ê¸°ë¡/ì¢ë£ -->\r\n");
      out.write("\t\t\t\t\t<a><i class=\"fa fa-quote-left\" id=\"recordStart\"style=\"font-size: 30px;\"></i></a>&nbsp;\r\n");
      out.write("\t\t\t\t\t<a><i class=\"fa fa-quote-right\" id=\"recordEnd\" style=\"font-size: 30px;\"></i></a>&nbsp;\r\n");
      out.write("\t\t\t\t\t<!-- ê²°ë¡  íê·¸ -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      <!-- end: content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- start: Mobile -->\r\n");
      out.write("      <div id=\"mimin-mobile\" class=\"reverse\">\r\n");
      out.write("        <div class=\"mimin-mobile-menu-list\">\r\n");
      out.write("            <div class=\"col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft\">\r\n");
      out.write("                <ul class=\"nav nav-list\">\r\n");
      out.write("                    <li class=\"active ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa-home fa\"></span>Dashboard \r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                          <li><a href=\"dashboard-v1.html\">Dashboard v.1</a></li>\r\n");
      out.write("                          <li><a href=\"dashboard-v2.html\">Dashboard v.2</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa-diamond fa\"></span>Layout\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"topnav.html\">Top Navigation</a></li>\r\n");
      out.write("                        <li><a href=\"boxed.html\">Boxed</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa-area-chart fa\"></span>Charts\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"chartjs.html\">ChartJs</a></li>\r\n");
      out.write("                        <li><a href=\"morris.html\">Morris</a></li>\r\n");
      out.write("                        <li><a href=\"flot.html\">Flot</a></li>\r\n");
      out.write("                        <li><a href=\"sparkline.html\">SparkLine</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-pencil-square\"></span>Ui Elements\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"color.html\">Color</a></li>\r\n");
      out.write("                        <li><a href=\"weather.html\">Weather</a></li>\r\n");
      out.write("                        <li><a href=\"typography.html\">Typography</a></li>\r\n");
      out.write("                        <li><a href=\"icons.html\">Icons</a></li>\r\n");
      out.write("                        <li><a href=\"buttons.html\">Buttons</a></li>\r\n");
      out.write("                        <li><a href=\"media.html\">Media</a></li>\r\n");
      out.write("                        <li><a href=\"panels.html\">Panels & Tabs</a></li>\r\n");
      out.write("                        <li><a href=\"notifications.html\">Notifications & Tooltip</a></li>\r\n");
      out.write("                        <li><a href=\"badges.html\">Badges & Label</a></li>\r\n");
      out.write("                        <li><a href=\"progress.html\">Progress</a></li>\r\n");
      out.write("                        <li><a href=\"sliders.html\">Sliders</a></li>\r\n");
      out.write("                        <li><a href=\"timeline.html\">Timeline</a></li>\r\n");
      out.write("                        <li><a href=\"modal.html\">Modals</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                       <span class=\"fa fa-check-square-o\"></span>Forms\r\n");
      out.write("                       <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"formelement.html\">Form Element</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Wizard</a></li>\r\n");
      out.write("                        <li><a href=\"#\">File Upload</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Text Editor</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-table\"></span>Tables\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"datatables.html\">Data Tables</a></li>\r\n");
      out.write("                        <li><a href=\"handsontable.html\">handsontable</a></li>\r\n");
      out.write("                        <li><a href=\"tablestatic.html\">Static</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a href=\"calendar.html\">\r\n");
      out.write("                         <span class=\"fa fa-calendar-o\"></span>Calendar\r\n");
      out.write("                      </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-envelope-o\"></span>Mail\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"mail-box.html\">Inbox</a></li>\r\n");
      out.write("                        <li><a href=\"compose-mail.html\">Compose Mail</a></li>\r\n");
      out.write("                        <li><a href=\"view-mail.html\">View Mail</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"ripple\">\r\n");
      out.write("                      <a class=\"tree-toggle nav-header\">\r\n");
      out.write("                        <span class=\"fa fa-file-code-o\"></span>Pages\r\n");
      out.write("                        <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"forgotpass.html\">Forgot Password</a></li>\r\n");
      out.write("                        <li><a href=\"login.html\">SignIn</a></li>\r\n");
      out.write("                        <li><a href=\"reg.html\">SignUp</a></li>\r\n");
      out.write("                        <li><a href=\"article-v1.html\">Article v1</a></li>\r\n");
      out.write("                        <li><a href=\"search-v1.html\">Search Result v1</a></li>\r\n");
      out.write("                        <li><a href=\"productgrid.html\">Product Grid</a></li>\r\n");
      out.write("                        <li><a href=\"profile-v1.html\">Profile v1</a></li>\r\n");
      out.write("                        <li><a href=\"invoice-v1.html\">Invoice v1</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li class=\"ripple\"><a class=\"tree-toggle nav-header\"><span class=\"fa \"></span> MultiLevel  <span class=\"fa-angle-right fa right-arrow text-right\"></span> </a>\r\n");
      out.write("                      <ul class=\"nav nav-list tree\">\r\n");
      out.write("                        <li><a href=\"view-mail.html\">Level 1</a></li>\r\n");
      out.write("                        <li><a href=\"view-mail.html\">Level 1</a></li>\r\n");
      out.write("                        <li class=\"ripple\">\r\n");
      out.write("                          <a class=\"sub-tree-toggle nav-header\">\r\n");
      out.write("                            <span class=\"fa fa-envelope-o\"></span> Level 1\r\n");
      out.write("                            <span class=\"fa-angle-right fa right-arrow text-right\"></span>\r\n");
      out.write("                          </a>\r\n");
      out.write("                          <ul class=\"nav nav-list sub-tree\">\r\n");
      out.write("                            <li><a href=\"mail-box.html\">Level 2</a></li>\r\n");
      out.write("                            <li><a href=\"compose-mail.html\">Level 2</a></li>\r\n");
      out.write("                            <li><a href=\"view-mail.html\">Level 2</a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"credits.html\">Credits</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>       \r\n");
      out.write("      </div>\r\n");
      out.write("      <button id=\"mimin-mobile-menu-opener\" class=\"animated rubberBand btn btn-circle btn-danger\">\r\n");
      out.write("        <span class=\"fa fa-bars\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("       <!-- end: Mobile -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/chatbox.jsp(194,15) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
