/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-21 06:46:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class storage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1459747375077L));
    _jspx_dependants.put("jar:file:/C:/dev/jado_공은아/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectSample/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"resources/js/jquery-2.2.2.min.js\"></script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".fileBox{\r\n");
      out.write("border: 1px solid gray;\r\n");
      out.write("display: inline-block;\r\n");
      out.write("width: 100px;\r\n");
      out.write("height: 100px;\r\n");
      out.write("margin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"button\" id=\"showStorage\" value=\"스토리지보기\">\r\n");
      out.write("<input type=\"button\" id=\"showMeetingBookContainer\" value=\"회의록보기\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\" style=\"display: none\">\r\n");
      out.write("\t<div id=\"themeList\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"fileList\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form id=\"saveFile\" action=\"saveFile\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"thmNum\" id=\"thmNum\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"proNum\" id=\"proNum\">\r\n");
      out.write("\t<input type=\"file\" name=\"file\" id=\"savefile\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<input type=\"button\" id=\"save\" value=\"저장\">\r\n");
      out.write("\t<input type=\"button\" id=\"delete\" value=\"삭제\">\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"meetingBookContainer\" style=\"display:none; \">\r\n");
      out.write("\t<div  id=\"themeList\">\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"BookList\" >\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" name=\"thmNum\" id=\"thmNum\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"proNum\" id=\"proNum\">\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\tvar url = window.location.href;\r\n");
      out.write("\tvar arr = url.split(\"=\")\r\n");
      out.write("\tvar proNum = arr[1]\r\n");
      out.write("\t$('#showStorage').on('click',function(){\r\n");
      out.write("\t\t$('#meetingBookContainer').css('display', 'none')\r\n");
      out.write("\t\t$('#container').css('display', 'block')\r\n");
      out.write("\t})\r\n");
      out.write("\t$('#showMeetingBookContainer').on('click',function(){\r\n");
      out.write("\t\t$('#container').css('display', 'none')\r\n");
      out.write("\t\t$('#meetingBookContainer').css('display', 'block')\r\n");
      out.write("\t})\t\r\n");
      out.write("\t$('.BookthmNum').on('click',function(){\r\n");
      out.write("\t\tthmNum = $(this).val();\r\n");
      out.write("\t\t$(\"#thmNum\").val(thmNum)\r\n");
      out.write("\t\tvar mydata={\r\n");
      out.write("\t\t\t\t\"thmNum\" : thmNum\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tmydata = JSON.stringify(mydata);\r\n");
      out.write("\t\t\tmydata=$.ajax({\r\n");
      out.write("\t\t\t\tmethod:\"post\"\r\n");
      out.write("\t\t\t\t,url:\"getBookList\"\r\n");
      out.write("\t\t\t\t,data:mydata\r\n");
      out.write("\t\t\t\t,dataType:\"json\"\r\n");
      out.write("\t\t\t\t,contentType:\"application/json;charset=utf-8\"\r\n");
      out.write("\t\t\t\t,success:function(response){\r\n");
      out.write("\t\t\t\t\t$('#BookList').empty();\r\n");
      out.write("\t\t\t\t\tvar cnt=0;\r\n");
      out.write("\t\t\t\t\tfor(var row =0; row<Math.ceil(response.length/5);row++){\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfor(var a=0;a<5;a++ ){\r\n");
      out.write("\t\t\t\t\t\t$('#BookList').append(\r\n");
      out.write("\t\t\t\t\t\t\t\"<div class = 'fileBox'><a href='viewBook?thmNum=\"+response[cnt].thmNum\r\n");
      out.write("\t\t\t\t\t\t\t+\"&chatDate=\"+response[cnt].chatDate+\"'>\"+response[cnt].chatDate+\"</a></div>\"\t\t\r\n");
      out.write("\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$('#fileList').append('<br />')\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},error:function(response){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$('.thmNum').on('click',function(){\r\n");
      out.write("\t\tthmNum = $(this).val();\r\n");
      out.write("\t\t$(\"#thmNum\").val(thmNum)\r\n");
      out.write("\t\tvar mydata={\r\n");
      out.write("\t\t\t\t\"thmNum\" : thmNum\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\tmydata = JSON.stringify(mydata);\r\n");
      out.write("\t\t\tmydata=$.ajax({\r\n");
      out.write("\t\t\t\tmethod:\"post\"\r\n");
      out.write("\t\t\t\t,url:\"getStgList\"\r\n");
      out.write("\t\t\t\t,data:mydata\r\n");
      out.write("\t\t\t\t,dataType:\"json\"\r\n");
      out.write("\t\t\t\t,contentType:\"application/json;charset=utf-8\"\r\n");
      out.write("\t\t\t\t,success:function(response){\r\n");
      out.write("\t\t\t\t\tvar cnt=0;\r\n");
      out.write("\t\t\t\t\t$('#fileList').empty();\r\n");
      out.write("\t\t\t\t\tfor(var row =0; row<Math.ceil(response.length/5);row++){\r\n");
      out.write("\t\t\t\t\t\tfor(var a=0;a<5;a++ ){\r\n");
      out.write("\t\t\t\t\t\t\t$('#fileList').append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"<div class = 'fileBox'><a href='download?fileName=\"+response[cnt].thmNum+\"_\"+response[cnt].fileName\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+\"'>\"+response[cnt].fileName+\"</a></div>\"\t\t\r\n");
      out.write("\t\t\t\t\t\t\t)\r\n");
      out.write("\t\t\t\t\t\t\tcnt++;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$('#fileList').append('<br />')\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},error:function(response){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t$('#save').on('click',function(){\r\n");
      out.write("\t\t$('#savefile').trigger('click');\r\n");
      out.write("\t     var val = $(\"#savefile\").val();\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#savefile\").change(function(){\r\n");
      out.write("\t\tvar fileName = $(this).val();\r\n");
      out.write("\t\t$('#proNum').val(proNum)\r\n");
      out.write("\t\t$('#saveFile').submit();\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/storage.jsp(27,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("theme");
    // /WEB-INF/views/storage.jsp(27,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/storage.jsp(27,2) '${themeList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${themeList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\t<li><input type=\"radio\" name=\"thmNum\" class=\"thmNum\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.thmNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.themeName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.thmNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</li>\t\t\t\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/storage.jsp(50,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("theme");
    // /WEB-INF/views/storage.jsp(50,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/storage.jsp(50,2) '${themeList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${themeList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\r\n");
          out.write("\t\t\t<li><input type=\"radio\" name=\"thmNum\" class=\"BookthmNum\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.thmNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.themeName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme.thmNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</li>\t\t\t\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
