DROP TABLE USER_TBL;

CREATE TABLE USER_TBL(
	USERID VARCHAR2(20) PRIMARY KEY,
	USERPASSWORD VARCHAR2(20) NOT NULL,
	USERNAME VARCHAR2(30) NOT NULL
);

INSERT INTO USER_TBL
VALUES
('user00','user00','user00');

SELECT * FROM USER_TBL;

COMMIT;